### ISSUE TITLE
Add support for jms serializer groups

### ISSUE THREAD

**Issue by natebrunette** [tebru/retrofit-php#11]

**Comment by ivorisoutdoors** [comment]
What would you think about using an annotation for creating serialization contexts? You could modify the context on each method rather than service wide.

I wrote up something quick that would show what that would look like. https://github.com/mloberg/retrofit-php/tree/feature/context-annotation

**Comment by natebrunette** [comment]
Just at a glance, this looks good.  I'll take a look tomorrow.

**Comment by ivorisoutdoors** [comment]
Cool. There aren't any tests, so I'll need to write those. We'll also probably want to work on a DeserializationContext annotation, which should look almost the same, but with different options.

**Comment by natebrunette** [comment]
Resolved with #25
