### ISSUE TITLE
Lack of registered services generates cache file that fails to parse

### ISSUE THREAD

**Issue by konrness** [tebru/retrofit-php#2]
If there are no registered services, when the Cache Writer calls clean() it generates an empty file with just "<?php". PHP will not parse this as valid PHP unless there is a new line after the opening PHP tag.

https://github.com/tebru/retrofit-php/blob/master/src/Cache/CacheWriter.php#L99

Need to change '<?php' to "<?php\n".

**Comment by natebrunette** [comment]
Do you need a version update?
