### ISSUE TITLE
Bump JMS Serializer to Latest Release

### ISSUE THREAD

**Issue by ReservedDeveloper** [tebru/retrofit-php#28]
This flies directly in the face of #22, but it'd be great to see the composer dependency for jms/serializer updated to ~1.0. Not sure what implications that has on the library, but suspecting that's a quicker thing to investigate than adding in all the adapters for serializer behavior that the other ticket will require.

**Comment by natebrunette** [comment]
Hey Daniel!

I did see that they recently released a stable version.  I've hesitated upgrading since so many people are using the latest unstable.  I'm going to test what breaks with the 1.0 release to see how feasible it would be to relax that dependency.

**Comment by natebrunette** [comment]
@ReservedDeveloper I tried using v1.0 and all the tests passed.  It doesn't really look like much has changed.  It's currently on master.  I'm planning on another release sometime this week, but I can do one now if you need it right away.

Out of curiosity, is there something in the 1.0 release that you need to use?

**Comment by ReservedDeveloper** [comment]
Dang, just beat me to it! Was going to let the tests run while chatting with @gideonfell yesterday, but figured out phpunit on my local VM seems to be borked (as an aside, considered setting phpunit as a dev dependency for the project?). 

As far as rationale, the version bump was largely out of convenience. A lot of our internal libraries set latest stable as the dependency. Don't know if we're using any particular functionality from v1. That said, I figured it was easier to see if you'd been exploring a version bump than trying to rationalize why we need to downgrade our internal dependencies :smile:. 

Feel free to do w/e other stuff you need to for your release. I'll just use ~~my fork to bump it~~ dev-master in the meantime.

**Comment by natebrunette** [comment]
Alright, sounds good.  PHPUnit is a dev dependency.  You can run `vendor/bin/phpunit` to run it.  The instructions aren't up to date, though.  You need to install and start canned first.
1. `npm install canned`
2. `nohup node ./node_modules/canned/bin/canned -p 5000 tests/canned >/dev/null 2>&1 &`

**Comment by natebrunette** [comment]
This now exists in the 2.2 version
