### ISSUE TITLE
Guzzle 5 Events Not Working

### ISSUE THREAD

**Issue by ivorisoutdoors** [tebru/retrofit-php#50]
The Guzzle 5 event emitter doesn't seem to be working in the new (2.x) version of Retrofit.

In some very basic debugging, I found that the Guzzle transaction was not using the EventEmitter that was attached to the Client.

**Comment by natebrunette** [comment]
This should be resolved by updating the [tebru/retrofit-http-clients](https://github.com/tebru/retrofit-http-clients) library.
