### ISSUE TITLE
Dynamic Headers

### ISSUE THREAD

**Issue by ivorisoutdoors** [tebru/retrofit-php#52]
It would be useful to set headers using logic instead of just being a simple string. One use case of this is to set X-Forwarded-For to the end user's IP.

**Comment by natebrunette** [comment]
Is it possible to use the event system for this?

**Comment by ivorisoutdoors** [comment]
That solves the issue.

**Comment by MDXDave** [comment]
Can someone please provide an example? @natebrunette @mloberg

**Comment by ivorisoutdoors** [comment]
@MDXDave ~~If you're using Guzzle, you would use the event system (v5) or middleware (v6) to modify the request directly. Check out the [Guzzle docs](http://docs.guzzlephp.org/en/latest/handlers-and-middleware.html).~~

See @natebrunette comment below. We ended up using Retrofit's event system because we didn't have to worry about what version of Guzzle we were using.

**Comment by natebrunette** [comment]
@MDXDave I really need to update the docs, but you can also use the event system.  Set a Symfony event dispatcher to the builder, then add a subscriber that listens for `retrofit.beforeSend`.  You'll receive a PSR-7 request object on the event.  Modify it, then set the new request object (because it's immutable) back to the event.

**Comment by MDXDave** [comment]
Thanks for your answers. And yes, the docs are not completely :smirk_cat: 

Working solution for others with the same problem below.

``` php
$dispatcher = new EventDispatcher();
$dispatcher->addListener('retrofit.beforeSend', function (BeforeSendEvent $event) use(&$accessToken) {
      $request = $event->getRequest()->withAddedHeader("Authorization", "Bearer ".$accessToken);
      $event->setRequest($request);
});

return RestAdapter::builder()->setEventDispatcher($dispatcher)->setBaseUrl(....)->build()->create(...::class);
```
