### ISSUE TITLE
Is it possible to use lambdas as a callbacks instead of Callback object?

### ISSUE THREAD

**Issue by molchanoviv** [tebru/retrofit-php#62]
I found that retrofit-php supports asynchronous calls but as callbacks it requires an instance of \Tebru\Retrofit\Http\Callback Such a callback is OK in Java since it supports lambdas only starting from 8 version but it supports anonymous classes. In php though it's not OK because php supports lambdas very long time but it supports anonymous classes only starting from php7. So I need to create a class which implements Callback interface somewhere else then create an instance of this class and only after that pass it to my client function. It's very inconvenient. So I wonder if it possible to use success/failure lambdas to handle response asynchronously?

**Comment by natebrunette** [comment]
How would you imagine this working from a user standpoint?

``` php
interface Foo
{
    public function bar(callable $success, callable $failure);
}
```

Something like this?  I considered this, but I thought that having to pass two anonymous function into the method would be a lot less pleasant than creating another class.

**Comment by molchanoviv** [comment]
Yep exactly. I think it's much more convenient then class because it requires less steps to do.

**Comment by natebrunette** [comment]
If you have time, please submit a bc pull request.  I don't really have the time right now.  I'm working on getting v2.9 wrapped up and then getting started on v3.

Keep in mind, Retrofit 3 will only support php 7, so this change will get immediately deprecated when that's released in favor of anonymous classes.

**Comment by molchanoviv** [comment]
Ok

**Comment by natebrunette** [comment]
If you work on it, take a look into wrapping the success/failure into a class implementing the callback.  That's probably the route I'd take.

**Comment by molchanoviv** [comment]
Ok. I'll think about it.

**Comment by natebrunette** [comment]
Lambda's will be supported in version 3
