### ISSUE TITLE
PhpParser/Parser cannot be instatiated

### ISSUE THREAD

**Issue by epfremmer** [tebru/retrofit-php#71]
PhpParser/Parser changed to an interface in **nikic/php-parser: ^2.0** causing:

```bash
Cannot instantiate interface PhpParser\Parser in /bla/bla/bla/vendor/tebru/retrofit-php/src/Generation/Printer/ArrayPrinter.php on line 41
```

I think changing:

```php
if (null === $parser) {
    $parser = new Parser(new Lexer());
}
```

To either using the PhpParser factory instead:

```php
use PhpParser\ParserFactory;
$parser = (new ParserFactory)->create(ParserFactory::PREFER_PHP7);
```

or always passing in the parser argument to use in the ArrayPrintyer.

A temporary workaround for this is to (i think) install **tebru/dyanmo:0.3.1**:

```bash
composer require tebru/dyanmo:0.3.1
```

**Comment by natebrunette** [comment]
This should be resolved with dynamo version 0.3.3.
