### ISSUE TITLE
Using @ResponseBody with arrays?

### ISSUE THREAD

**Issue by nrutman** [tebru/retrofit-php#77]
Hello, I'm trying to use the `ResponseBody` annotation to transform a response that returns an array of objects. Does the annotation support array syntax? I was expecting to use something like…

```
@ResponseBody("MyNamespace/MyClass[]")
```

…but I'm getting a `ResponseHandlingFailedException: "Retrofit: Could not convert response body"` exception.

**Comment by nrutman** [comment]
Note that I am using a Converter factory that leverages the JMS Serializer. So even if that makes it difficult to provide an answer, I'd love any tips on how to debug the issue. When I use a non-array endpoint/annotation, everything works great!

**Comment by natebrunette** [comment]
I'm digging into the exact place we read this annotation, but my guess is that the short syntax isn't supported. Assuming your namespace correctly uses `\` instead of `/`, you should be able to do `array<MyNamespace\MyClass>`.

**Comment by natebrunette** [comment]
Yeah, it just gets passed into a new `TypeToken` (https://github.com/tebru/php-type) which doesn't currently support that syntax.

**Comment by nrutman** [comment]
@natebrunette not sure about your last comment…using JMS I passed `array<T>` (where T represents the class in the array) and it properly deserialized the body!

Sorry for the dumb question...seems like it was more of a JMS question and less of a Retrofit-PHP question.
